export { AccordionsSection } from "./AccordionsSection"
export { PhotoGallerySection } from "./PhotoGallerySection"
export { PhotosSection } from "./PhotosSection"
export { QuoteSection } from "./QuoteSection"
export { TabsSection } from "./TabsSection"
export { TextSection } from "./TextSection"
